# Generated by Django 5.2.14 on 2026-05-11 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_scanresult_status_user_completed_at_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='scanresult',
            new_name='scanner_sca_user_id_31e6c5_idx',
            old_name='scanner_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='scanresult',
            new_name='scanner_sca_status_ee58a9_idx',
            old_name='scanner_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scanresult',
            new_name='scanner_sca_scan_ty_d061c8_idx',
            old_name='scanner_scan_type_idx',
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['-created_at'], name='scanner_sca_created_9c9c44_idx'),
        ),
    ]
