# Generated by Django 5.2.14 on 2026-05-13 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_reconsession_scanreport_scanresult_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanresult',
            old_name='session',
            new_name='recon_session',
        ),
        migrations.RemoveField(
            model_name='reconsession',
            name='tools_config',
        ),
        migrations.RemoveField(
            model_name='scanreport',
            name='critical_count',
        ),
        migrations.RemoveField(
            model_name='scanreport',
            name='high_count',
        ),
        migrations.RemoveField(
            model_name='scanreport',
            name='info_count',
        ),
        migrations.RemoveField(
            model_name='scanreport',
            name='low_count',
        ),
        migrations.RemoveField(
            model_name='scanreport',
            name='medium_count',
        ),
        migrations.RemoveField(
            model_name='scanreport',
            name='scan_ids',
        ),
        migrations.RemoveField(
            model_name='scanreport',
            name='session',
        ),
        migrations.AddField(
            model_name='scanreport',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='recon_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='scanner.reconsession'),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='scan_results',
            field=models.ManyToManyField(blank=True, related_name='reports', to='scanner.scanresult'),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='severity_counts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='findings_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
